name: Build

on:
  workflow_call:
    inputs:
      ecr_repository:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker イメージのビルド
        run: docker build -f batch/Dockerfile -t ${{ inputs.ecr_repository }}:${{ github.sha }} .
        working-directory: apps/spring-batch-app-v1

      - name: Docker イメージを tar に保存
        run: docker save ${{ inputs.ecr_repository }}:${{ github.sha }} -o image.tar

      - name: tar を artifact としてアップロード
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar
